"""Initial migration

Revision ID: 02fe5bb6bb78
Revises:
Create Date: 2025-10-13 21:13:14.014531

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "02fe5bb6bb78"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "produto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("preco_venda_litro", sa.Float(), nullable=False),
        sa.Column("preco_venda_barril_fechado", sa.Float(), nullable=False),
        sa.Column("volume_litros", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_produto_nome"), "produto", ["nome"], unique=False)
    op.create_table(
        "movimentoestoque",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo_movimento", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantidade", sa.Float(), nullable=False),
        sa.Column("custo_unitario", sa.Float(), nullable=True),
        sa.Column("data_movimento", sa.Date(), nullable=False),
        sa.Column("produto_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venda",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("dia_semana", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tipo_venda", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("cartao", sa.Float(), nullable=False),
        sa.Column("dinheiro", sa.Float(), nullable=False),
        sa.Column("pix", sa.Float(), nullable=False),
        sa.Column("custo_func", sa.Float(), nullable=True),
        sa.Column("custo_copos", sa.Float(), nullable=True),
        sa.Column("custo_boleto", sa.Float(), nullable=True),
        sa.Column("lucro", sa.Float(), nullable=False),
        sa.Column("observacoes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("quantidade_barris_vendidos", sa.Float(), nullable=True),
        sa.Column("preco_venda_litro_registrado", sa.Float(), nullable=True),
        sa.Column("produto_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("venda")
    op.drop_table("movimentoestoque")
    op.drop_index(op.f("ix_produto_nome"), table_name="produto")
    op.drop_table("produto")
    # ### end Alembic commands ###
