"""Tornar preco_venda_litro opcional

Revision ID: f7639c07bd65
Revises: 02fe5bb6bb78
Create Date: 2025-10-16 19:42:41.854788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7639c07bd65'
down_revision: Union[str, Sequence[str], None] = '02fe5bb6bb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('preco_venda_litro',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('preco_venda_litro',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
