name: Python Application CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint and Format with Ruff
      run: |
        # Verifica por erros de linting
        ruff check .
        # Verifica se o código está formatado corretamente
        ruff format --check .

    - name: Test with pytest
      run: |
        pytest
